<?php
/**
 * Created by PhpStorm.
 * User: rezowan
 * Date: 5/23/20
 * Time: 9:56 PM
 */

namespace Test\CalculateFeeBundle\DataSource;

use CalculateFeeBundle\Common\Contract\DataInterface;
use CalculateFeeBundle\DataSource\Data;
use JsonSchema\Exception\InvalidSchemaException;
use Mockery\MockInterface;
use PHPUnit\Framework\TestCase;

class DataTest extends TestCase
{
    /**
     * @var MockInterface
     */
    private $dataClass;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->dataClass = \Mockery::mock(Data::class);

    }

    public function testSetRateUrl()
    {
        $data = new Data();
        $exampleUrl = "http://example.com";

        $data->setRateUrl($exampleUrl);
        $this->assertIsString($data->getRateUrl());
        $this->assertEquals($exampleUrl, $data->getRateUrl());
    }

    public function testSetBinUrl()
    {
        $data = new Data();
        $exampleUrl = "http://example.com/bin/1234";

        $data->setBinUrl($exampleUrl);
        $this->assertIsString($data->getBinUrl());
        $this->assertEquals($exampleUrl, $data->getBinUrl());
    }


}